steps:
  - id: go_version
    name: "gcr.io/cloud-builders/go"
    args: ["version"]
    env: ["GOPATH=."]

  - name: golang
    entrypoint: /bin/bash
    args:
      - -c
      - |
        go test -v ./...

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      [
        "gcloud",
        "functions",
        "deploy",
        "func_4",
        "--entry-point=Greet",
        "--region=us-central1",
        "--source=.",
        "--trigger-http",
        "--runtime=go116",
      ]
