on:
  pull_request:
    branches: [main, master, dev]

name: pytest

jobs:
  deploy_functions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install_pytest
        shell: bash
        run: |
          pip install pytest

      - name: pytest
        shell: bash
        run: |
          # For every file in repo
          for i in $(ls); do
            # If it's a folder
            if [[ -d "$i" ]]; then
              cd $i
                is_py=0
                for f in $(ls); do
                  # Check if contains python files
                  if [[ $f == *.py ]]; then
                    is_py=$((is_py+1))
                  fi
                done
                # Run tests if it does
                if ((is_py == 0)); then
                  cd .. 
                  continue
                else
                  pip install -r requirements.txt
                  pytest
                  cd ..
                fi
            fi
          done
